services:
  api:
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT}:8000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /code/src
        - action: rebuild
          path: ./src
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8000/health" ]
      interval: 10s
      timeout: 3s
      retries: 5

  nginx:
    image: nginx:1.25
    ports:
      - "${NGINX_PORT}:80"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${MEDIA_PATH}:/var/www/documents:ro
    develop:
      watch:
        - action: rebuild
          path: ./nginx/nginx.conf

    depends_on:
      - api