events {}

http {
    upstream fastapi {
        server api:8000;
    }

    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        # Всё FastAPI
        location / {
            proxy_pass http://fastapi;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }

        # Медиа напрямую
        location /media/ {
            alias /var/www/documents/;
            autoindex on;
            access_log off;
            error_log /var/log/nginx/media.error.log debug;
            try_files $uri $uri/ =404;
        }
    }
}
